import Head from 'next/head'
import Theme from '../Theme'
import MobileMenu from '../components/MobileMenu/MobileMenu'
import { useMobileMenu } from '../Contexts/MobileMenuContext'
import Link from 'next/link'

export default function Home() {
  const { isVisibleMobileMenu } = useMobileMenu()
  return (
    <Theme>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isVisibleMobileMenu && <MobileMenu />}
      <h1>Home Page</h1>
      <Link href="http://localhost:3000/products/create">Create Products</Link>
    </Theme>
  )
}
