import Head from 'next/head'
import Theme from '../Theme'
import MobileMenu from '../components/MobileMenu/MobileMenu'
import { useMobileMenu } from '../Contexts/MobileMenuContext'
import Link from 'next/link'

export default function Home({ products }) {
  const { isVisibleMobileMenu } = useMobileMenu()
  return (
    <Theme>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isVisibleMobileMenu && <MobileMenu />}
      <h1>Home Page</h1>
      <Link href="http://localhost:3000/products/create">Create Products</Link>
    </Theme>
  )
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:5000/api/products/categories/28`)
  const products = await res.json()

  // Pass data to the page via props
  return { props: { products } }
}
